[package]
name = "griffin-dalby/sawdust"
version = "1.4.4"
registry = "https://github.com/UpliftGames/wally-index"
license = "Apache2"
realm = "shared"

exclude = [
    "build",
    "util",
    ".gitignore",
    "CHANGELOG.md",
    "README.md",
    "wally.lock",
]

[dependencies]
testez = "roblox/testez@0.4.1"