name: Build Rojo Project

on:
  push:
    branches:
      - main
    paths:
      - "wally.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup aftman and install tools
        uses: ok-nick/setup-aftman@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wally packages
        run: wally install

      - name: Build Rojo Project
        run: rojo build default.project.json --output build.rbxl

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: rojo-build
          path: build.rbxl

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple

      - name: Upload Release Asset
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} build.rbxl
